import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";
import Header from "./_component/Header";
import "./globals.css";
import Footer from "./_component/Footer";
import NextTopLoader from "nextjs-toploader";
import { Providers, SessionProviders, UserProviders } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.className} dark:bg-body bg-white`}
                suppressHydrationWarning
            >
                <SessionProviders>
                    <Providers>
                        <UserProviders>
                            <NextTopLoader
                                color="#6495ed"
                                showSpinner={false}
                            />
                            {/* <DetectDevTool /> */}
                            <div className="flex flex-col justify-between min-h-screen">
                                <Header />
                                <AntdRegistry>{children}</AntdRegistry>
                                <Footer />
                            </div>
                        </UserProviders>
                    </Providers>
                </SessionProviders>
            </body>
        </html>
    );
}
